Fixed a bug in leitner box SubmitChanges() function. Adds support to be compiled against wxGTK 2.8 series. Updated files for 2009 copyright note. Updated NEWS file.

diff --git a/xfardic-src/configure b/xfardic-src/configure
--- a/xfardic-src/configure
+++ b/xfardic-src/configure
@@ -2008,7 +2008,7 @@ fi
 
 # Define the identity of the package.
  PACKAGE=xfardic
- VERSION=0.11.4
+ VERSION=0.11.5
 
 
 cat >>confdefs.h <<_ACEOF
@@ -4227,7 +4227,9 @@ fi
 LIBWX_INCLUDEDIR=""
 for d in 			\
     /usr/include/wx-2.6/wx\
-    $prefix/include/wx-2.6/wx
+    $prefix/include/wx-2.6/wx\
+    /usr/include/wx-2.8/wx\
+    $prefix/include/wx-2.8/wx
 do
     if test -f "$d/wx.h" ; then
 	LIBWX_INCLUDEDIR="$d"
@@ -4235,8 +4237,8 @@ do
     fi
 done
 if test "x$LIBWX_INCLUDEDIR" = "x"; then
-    { { echo "$as_me:$LINENO: error: You should have wxGTK header files! Install libwxgtk2.6-dev" >&5
-echo "$as_me: error: You should have wxGTK header files! Install libwxgtk2.6-dev" >&2;}
+    { { echo "$as_me:$LINENO: error: You should have wxGTK header files! Install libwxgtk2.6-dev or libwxgtk2.8-dev" >&5
+echo "$as_me: error: You should have wxGTK header files! Install libwxgtk2.6-dev or libwxgtk2.8-dev" >&2;}
    { (exit 1); exit 1; }; }
 else
     echo "checking for wx.h...yes"
